config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'

  }

  devise_scope :user do
    get 'admin/login', to: 'users/sessions#new', defaults: { role: 'admin' }
    get 'attendant/login', to: 'users/sessions#new', defaults: { role: 'attendant' }
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  # Rota personalizada para pesquisa
  get 'visitors/search', to: 'visitors#search'
  get 'visitorsjs/searchjs', to: 'visitorsjs#searchjs'

  # Rotas para visitantes e visitas
  resources :visitors, only: [:new, :create]
  resources :visits, only: [:new, :create]

  # Rotas para visitantes e visitas com JavaScript
  resources :visitorsjs, only: [:new, :create]
  resources :visitsjs, only: [:new, :create]

  resources :units
  resources :positions
  resources :departments
  resources :employees do
    collection do
      get 'departments_por_unit'
      get 'search'
    end
  end

  root "home#index"

end

app/models/position.rb
class Position < ApplicationRecord

  has_many :employees, dependent: :restrict_with_error

  validates :name, presence: true, uniqueness: true

  scope :active, -> { where(active: true) }


end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  def index
    @positions = Position.all
  end

  def show
    @employees = @position.employees
  end

  def new
    @position = Position.new
  end

  def create
    @position = Position.new(position_params)
    if @position.save
      redirect_to positions_path, notice: 'Função cadastrada com sucesso.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @position.update(position_params)
      redirect_to positions_path, notice: 'Função atualizada com sucesso.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @position.destroy
      redirect_to positions_path, notice: 'Função excluída com sucesso.'
    else
      redirect_to positions_path, alert: 'Não é possível excluir esta função pois ela possui registros associados.'
    end
  end

  private

  def set_position
    @position = Position.find(params[:id])
  end

  def position_params
    params.require(:position).permit(:name, :description, :active)
  end
end

app/views/positions/_form.html.erb
    <%= simple_form_for(@position, wrapper: :vertical_form, html: { class: 'row g-3' }) do |f| %>

      <div class="col-md-6">
        <%= f.input :name,
                    input_html: { class: 'form-control' },
                    label_html: { class: 'form-label' },
                    wrapper_html: { class: 'mb-3' },
                    placeholder: 'Nome da unidade' %>
      </div>

      <div class="col-12">
        <%= f.input :active,
                    as: :boolean,
                    wrapper_html: { class: 'form-check form-switch' },
                    input_html: { class: 'form-check-input' },
                    label_html: { class: 'form-check-label' } %>
      </div>

      <div class="col-12 d-flex justify-content-end">
        <%= f.button :submit, class: 'btn btn-success' %>
        <%= link_to 'Cancelar', positions_path, class: 'btn btn-secondary ms-2 mr-5' %>
      </div>
    <% end %>

app/views/positions/_position.html.erb
<div id="<%= dom_id position %>">
  <p>
    <strong>Name:</strong>
    <%= position.name %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= position.active %>
  </p>

</div>

app/views/positions/edit.html.erb
<div class="container rounded bg-dark text-white p-4 mt-4">
  <div class="row mb-3">

    <% content_for :title, "Editing position" %>

    <h1>Editing position</h1>

    <%= render "form", position: @position %>

  </div>
</div>

app/views/positions/index.html.erb
<% content_for :title, "Unidades" %>

<div class="container rounded bg-dark text-white p-4 mt-4">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="text-light">Funções</h1>
    <%= link_to "Nova Função", new_position_path, class: 'btn btn-success' %>
  </div>

  <% flash.each do |key, value| %>
    <div data-controller="flash-message" data-action="click->flash-message#removeMessage" id="flash-message" class="flash <%= key %> alert alert-danger bold text-black" data-flash-message-target="message"><%= value %></div>
  <% end %>

  <div class="table-responsive">
    <table class="table table-striped table-dark table-hover">
      <thead>
        <tr>
          <th>Nome</th>
          <th style="width: 150px;">Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @positions.each do |position| %>
          <tr>
            <td><%= position.name %></td>
            <td>
              <div class="d-flex justify-content-around">
                <%= link_to position_path(position), class: 'btn btn-sm btn-outline-light', data: { turbo_frame: "_top" } do %>
                  <i class="bi bi-eye"></i>
                <% end %>
                <%= link_to edit_position_path(position), class: 'btn btn-sm btn-outline-light', data: { turbo_frame: "_top" } do %>
                  <i class="bi bi-pencil"></i>
                <% end %>
                <%= link_to position, class: "btn btn-sm btn-outline-danger me-2", title: "Excluir", 
                    data: { method: :delete, confirm: "Tem certeza que deseja excluir esta função?" } do %>
                    <i class="bi bi-trash"></i>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<script>
  document.addEventListener("DOMContentLoaded", function() {
    var flashMessage = document.getElementById('flash-message');
    if (flashMessage) {
      setTimeout(function() {
        flashMessage.style.display = 'none';
      }, 5000); // Remove the flash message after 5 seconds

      document.addEventListener('click', function() {
        flashMessage.style.display = 'none';
      });
    }
  });
</script>

app/views/positions/new.html.erb
<div class="container rounded bg-dark text-white p-4 mt-4">
  <div class="row mb-3">

    <% content_for :title, "New position" %>

    <h1>New position</h1>

    <%= render "form", position: @position %>

  </div>
</div>

app/views/positions/show.html.erb
<div class="container rounded bg-dark text-white p-4 mt-4">
  <div class="row mb-3">

    <p style="color: green"><%= notice %></p>

    <%= render @position %>

    <div class="col-12 d-flex justify-content-end">
      <%= link_to edit_position_path(@position), class: 'btn btn-sm btn-outline-light', title: "Editar", ata: { turbo_frame: "_top" } do %>
                  <i class="bi bi-pencil-fill"></i>
      <% end %>
      <%= link_to positions_path, class: 'btn btn-sm btn-outline-light ms-2', title: "Voltar", data: { turbo_frame: "_top" } do %>
                  <i class="bi bi-reply-fill"></i>
      <% end %>
    </div>
  </div>
</div>