config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'

  }

  devise_scope :user do
    get 'admin/login', to: 'users/sessions#new', defaults: { role: 'admin' }
    get 'attendant/login', to: 'users/sessions#new', defaults: { role: 'attendant' }
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  # Rota personalizada para pesquisa
  get 'visitors/search', to: 'visitors#search'
  get 'visitorsjs/searchjs', to: 'visitorsjs#searchjs'

  # Rotas para visitantes e visitas
  resources :visitors, only: [:new, :create]
  resources :visits, only: [:new, :create]

  # Rotas para visitantes e visitas com JavaScript
  resources :visitorsjs, only: [:new, :create]
  resources :visitsjs, only: [:new, :create]

  resources :units
  resources :positions
  resources :departments
  resources :employees do
    collection do
      get 'departments_por_unit'
      get 'search'
    end
  end

  root "home#index"

end

app/models/unit.rb
class Unit < ApplicationRecord

  has_many :unit_departments
  has_many :departments, through: :unit_departments
  has_many :employees, dependent: :restrict_with_error
  has_many :visits, dependent: :restrict_with_error

  validates :name, presence: true, uniqueness: true

  scope :active, -> { where(active: true) }

  default_scope { order(:name) }

  def to_s
    name
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_unit, only: [:show, :edit, :update, :destroy, :employees]

  def index
    @units = Unit.all
  end

  def show

  end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(unit_params)
    if @unit.save
      redirect_to units_path, notice: 'Unidade cadastrada com sucesso.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @unit.update(unit_params)
      redirect_to units_path, notice: 'Unidade atualizada com sucesso.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @unit.destroy
      redirect_to units_path, notice: 'Unidade excluída com sucesso.'
    else
      redirect_to units_path, alert: 'Não é possível excluir esta unidade pois ela possui registros associados.'
    end
  end

  def employees
    @employees = @unit.employees.active.includes(:department, :position)

    respond_to do |format|
      format.json { render json: @employees.map { |e| { id: e.id, name: e.name, department_name: e.department.name, position_name: e.position.name } } }
    end
  end

  private

  def set_unit
    @unit = Unit.find(params[:id])
  end

  def unit_params
    params.require(:unit).permit(:name, :description, :active)
  end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
    <%= simple_form_for(@unit, wrapper: :vertical_form, html: { class: 'row g-3' }) do |f| %>

      <div class="col-md-6">
        <%= f.input :name,
                    input_html: { class: 'form-control' },
                    label_html: { class: 'form-label' },
                    wrapper_html: { class: 'mb-3' },
                    placeholder: 'Nome da unidade' %>
      </div>

      <div class="col-md-6">
        <%= f.input :description,
                    input_html: { class: 'form-control' },
                    label_html: { class: 'form-label' },
                    wrapper_html: { class: 'mb-3' },
                    placeholder: 'Descrição da unidade' %>
      </div>

      <div class="col-12">
        <%= f.input :active,
                    as: :boolean,
                    wrapper_html: { class: 'form-check form-switch' },
                    input_html: { class: 'form-check-input' },
                    label_html: { class: 'form-check-label' } %>
      </div>

      <div class="col-12 d-flex justify-content-end">
        <%= f.button :submit, class: 'btn btn-success' %>
        <%= link_to 'Cancelar', units_path, class: 'btn btn-secondary ms-2 mr-5' %>
      </div>
    <% end %>

app/views/units/_unit.html.erb
<div id="<%= dom_id unit %>">
  <p>
    <strong>Name:</strong>
    <%= unit.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= unit.description %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= unit.active %>
  </p>

</div>

app/views/units/edit.html.erb
<div class="container rounded bg-dark text-white p-4 mt-4">
  <div class="row mb-3">

    <% content_for :title, "Editing unit" %>

    <h1>Editing unit</h1>

    <%= render "form", unit: @unit %>

  </div>
</div>

app/views/units/index.html.erb
<% content_for :title, "Unidades" %>

<div class="container rounded bg-dark text-white p-4 mt-4">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="text-light">Unidades</h1>
    <%= link_to "Nova Unidade", new_unit_path, class: 'btn btn-success' %>
  </div>

  <% flash.each do |key, value| %>
    <div data-controller="flash-message" data-action="click->flash-message#removeMessage" id="flash-message" class="flash <%= key %> alert alert-danger bold text-black" data-flash-message-target="message"><%= value %></div>
  <% end %>

  <div class="table-responsive">
    <table class="table table-striped table-dark table-hover">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Descrição</th>
          <th style="width: 150px;">Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @units.each do |unit| %>
          <tr>
            <td><%= unit.name %></td>
            <td><%= unit.description.truncate(100) if unit.description %></td>
            <td>
              <div class="d-flex justify-content-around">
                <%= link_to unit_path(unit), class: 'btn btn-sm btn-outline-light', data: { turbo_frame: "_top" } do %>
                  <i class="bi bi-eye"></i>
                <% end %>
                <%= link_to edit_unit_path(unit), class: 'btn btn-sm btn-outline-light', data: { turbo_frame: "_top" } do %>
                  <i class="bi bi-pencil"></i>
                <% end %>
                <%= link_to unit, class: "btn btn-sm btn-outline-danger me-2", title: "Excluir", 
                    data: { method: :delete, confirm: "Tem certeza que deseja excluir esta unidade ?" } do %>
                    <i class="bi bi-trash"></i>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var flashMessage = document.getElementById('flash-message');
    if (flashMessage) {
      setTimeout(function() {
        flashMessage.style.display = 'none';
      }, 5000); // Remove the flash message after 5 seconds

      document.addEventListener('click', function() {
        flashMessage.style.display = 'none';
      });
    }
  });
</script> 

app/views/units/new.html.erb
<div class="container rounded bg-dark text-white p-4 mt-4">
  <div class="row mb-3">

    <% content_for :title, "New unit" %>

    <h1>New unit</h1>

    <%= render "form", unit: @unit %>

  </div>
</div>

app/views/units/show.html.erb
<div class="container rounded bg-dark text-white p-4 mt-4">
  <div class="row mb-3">

    <p style="color: green"><%= notice %></p>

    <%= render @unit %>

    <div class="col-12 d-flex justify-content-end">
      <%= link_to edit_unit_path(@unit), class: 'btn btn-sm btn-outline-light', title: "Editar", ata: { turbo_frame: "_top" } do %>
                  <i class="bi bi-pencil-fill"></i>
      <% end %>
      <%= link_to units_path, class: 'btn btn-sm btn-outline-light ms-2', title: "Voltar", data: { turbo_frame: "_top" } do %>
                  <i class="bi bi-reply-fill"></i>
      <% end %>
    </div>
  </div>
</div>