config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'

  }

  devise_scope :user do
    get 'admin/login', to: 'users/sessions#new', defaults: { role: 'admin' }
    get 'attendant/login', to: 'users/sessions#new', defaults: { role: 'attendant' }
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  # Rota personalizada para pesquisa
  get 'visitors/search', to: 'visitors#search'
  get 'visitorsjs/searchjs', to: 'visitorsjs#searchjs'

  # Rotas para visitantes e visitas
  resources :visitors, only: [:new, :create]
  resources :visits, only: [:new, :create]

  # Rotas para visitantes e visitas com JavaScript
  resources :visitorsjs, only: [:new, :create]
  resources :visitsjs, only: [:new, :create]

  resources :units
  resources :positions
  resources :departments
  resources :employees do
    collection do
      get 'departments_por_unit'
      get 'search'
    end
  end

  root "home#index"

end

app/views/layouts/OLDdevise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
     <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true, type: "module" %>
  </head>

  <body class=" d-flex flex-column">
    <div class="page page-center">
      <div class="container container-tight py-4">
        <%= yield %>
      </div>
    </div>
    <%= render "layouts/flash" %>
  </body>
</html>

app/views/layouts/_close_modal_script.html.erb
<script>
  closeVisitorModal();
</script>

app/views/layouts/_flash.html.erb
<%= turbo_frame_tag "flash" do %>
  <div id="flash-message">
    <% if notice %>
      <div data-controller="flash" data-flash-text-value="<%= notice %>" data-flash-type-value="success"></div>
    <% end %>
    <% if alert %>
      <div data-controller="flash" data-flash-text-value="<%= alert %>" data-flash-type-value="error"></div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'logo.svg', alt: 'Logo', style: 'height: 70px;' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? && current_user.admin? %>
          <li class="nav-item me-5">
            <%= link_to "Units", units_path, class: "btn btn-primary fw-bold", style: "border-radius: 40px;" %>
          </li>
          <li class="nav-item me-5 ">
            <%= link_to "Departments", departments_path, class: "btn btn-primary fw-bold", style: "border-radius: 40px;" %>
          </li>
          <li class="nav-item me-5">
            <%= link_to "Positions", positions_path, class: "btn btn-primary fw-bold", style: "border-radius: 40px;" %>
          </li>
          <li class="nav-item me-5">
            <%= link_to "Employees", employees_path, class: "btn btn-primary fw-bold", style: "border-radius: 40px;" %>
          </li>
        <% end %>

        <% if user_signed_in? && (current_user.admin? || current_user.attendant?) %>
          <li class="nav-item me-5">
            <%= link_to "Visits", new_visit_path, class: "btn btn-primary fw-bold", style: "border-radius: 40px;" %>
          </li>
        <% end %>

        <% if user_signed_in? %>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, style: "border-radius: 40px;", form: { class: "btn btn-danger d-inline" } %>
          </li>
        <% else%>
          <li class="nav-item">
            <%= button_to  "Login", new_user_session_path,  style: "border-radius: 40px;", form: { class: "btn btn-secondary d-inline fw-bold" } %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Visitor Management" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module", defer: true %>

    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/webcamjs/1.0.26/webcam.min.js" %>
    
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div id="">
     
      <%= yield %>
    </div>
    <%= render "layouts/flash" %>
  </body>
</html>